### ISSUE TITLE
Sentiment Analysis

### ISSUE THREAD

**Issue by perireddyvaka** [KIET-NEST-PROJECTS-KBH/E-3F-316#1]
Develop a model that can determine whether a given text expresses a 
positive, negative, or neutral sentiment

**Comment by pnkjshrma99** [comment]
# Step 1: Install the vaderSentiment library
# You can install it using pip:
# !pip install vaderSentiment

# Step 2: Import necessary libraries
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Step 3: Initialize the VADER analyzer
analyzer = SentimentIntensityAnalyzer()

# Step 4: Define a function to analyze sentiment
def analyze_sentiment(text):
    sentiment_score = analyzer.polarity_scores(text)
    
    if sentiment_score['compound'] >= 0.05:
        return 'positive'
    elif sentiment_score['compound'] <= -0.05:
        return 'negative'
    else:
        return 'neutral'

# Step 5: Test the sentiment analysis function
text1 = "I love this product, it's amazing!"
text2 = "I'm really disappointed with the service."
text3 = "This is just okay, nothing special."

sentiment1 = analyze_sentiment(text1)
sentiment2 = analyze_sentiment(text2)
sentiment3 = analyze_sentiment(text3)

print(f"Text 1 sentiment: {sentiment1}")
print(f"Text 2 sentiment: {sentiment2}")
print(f"Text 3 sentiment: {sentiment3}")
